name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # *** Usando o Platane/snk, que é a action mais atualizada (v3) ***
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Erick-Dean
          outputs: |
            # Este output é o que está referenciado no seu README.md
            dist/github-contribution-grid-snake.svg
      
      # *** Este passo é crucial para enviar o arquivo gerado para o branch 'output' ***
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
