name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/github-contribution-grid-snake@v2
        id: snake-gif
        with:
          github_user_name: Erick-Dean
          snake_snes: true
          output_path: /output/github-contribution-grid-snake.svg
