name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platypus-Code/github-contribution-grid-snake@v1
        id: snake-gif
        with:
          github_user_name: SEU_USUARIO_GITHUB # Mude para o seu usuário!
          snake_snes: true # Um estilo de animação
          output_path: /output/github-contribution-grid-snake.svg
